name: Print Software and Database Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print_software_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Node.js version
        run: node --version

      - name: Print npm version
        run: npm --version

      - name: Print Python version
        run: python3 --version

  print_database_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MongoDB Shell (mongosh) via Snap
        run: |
          sudo snap install mongosh --edge --devmode

      - name: Check MongoDB Shell version
        run: mongosh --version
