name: Print Software and Database Versions

on:
  push:
  workflow_dispatch:

jobs:
  print_software_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Node.js version
        run: node --version

      - name: Print npm version
        run: npm --version

      - name: Print Python version
        run: python3 --version

  print_database_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MongoDB Shell
        run: |
          wget -qO - https://pgp.mongodb.com/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.com/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Check MongoDB shell version
        run: mongosh --version
