name: JavaScript Code Linter

on:
  push:
    branches: [ main ]

jobs:
  JavaScriptCodeLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Biome (JS linter & formatter)
        run: |
          npm install --save-dev --save-exact @biomejs/biome

      - name: Run code style & syntax validation
        run: |
          npx @biomejs/biome check ProgramCode/*.js

